### ISSUE TITLE
What licence is this code available under?

### ISSUE THREAD

**Issue by kevinhendricks** [dpacbach/p-unzip#1]
Very clean and nice code.  Would love to adapt this to use Qt and QtConcurrent for use in Sigil (a free opensource epub editor) since some epubs (zips) now have over 1000 files inside.  But I could not find any license info on any of the files in your repo.

Please let me know what license this code is available under.

Thank you.

**Comment by no-more-secrets** [comment]
Thanks, I have added a `LICENSE.txt` file which applies to all files, it is the MIT license, which should hopefully allow you to do whatever you want with it.

If you decide to incorporate this somewhere, I'd be curious to see how you are using it :-)

Out of curiosity, what drives you to want a parallel unzipper?  Performance reasons?  If so, I would encourage you to do some profiling of the end result compared against a non-parallel approach to see if this library provides you any benefit.  I say that because, depending on the system/use case, unzipping can sometimes be an IO-bound operation, in which case parallelizing the extraction may not help much.  But it might, you just have to profile to know.  Once you get this library hooked into your code, you could run some tests by invoking the library with e.g. 8 threads vs. invoking it with 1 thread (the API should let you choose), which should give you a good idea of whether the parallelization is helping.

**Comment by kevinhendricks** [comment]
Very long loading time for large epubs (which are really just zips underneath) which have 1000's of xhtml files, images, and etc in each zip.  We need to be completely expand them as our editor wraps a resource object around each and caches file contents for speedy editing.

The loading time for large epubs can take from 5 to 10 seconds or more using a single threaded version of original minizip. 

Sigil is Qt based and they already support a QtConcurrent::mapped() so if I create a QList of zip entry objects and memory map the zip file using your Buffers approach and pre-create the required destination directories (while building up the list of zip entry objects), I am hoping to to at least cut that time down (if I am lucky).

Since most modern os use extra memory internally to greatly speed up buffered io and come with ssd drives with high bandwidth so I am hoping to see some improvement based on that.  

FWIW, If I decide to do this, I would just be extracting parts of your code.  Many of the things you do  such as the distribution and actual thread creation parts, figuring out how many threads to use, and etc.  are all wrapped in a cross-platform way by Qt. QByteArray's can already be mapped as io devices, and are reference counted with fast copy on write, etc.  And a Qt based app already keeps its own set of worker threads internally (so thread creation and  destruction will not impact speed).

Original minizip is not set up for multithreaded access, and though minizip_ng is thread safe, it really has none of the support routines to enable a multi-threaded unzip.

My first step will be to build your library "as is" on my macOS dev box, and then run tests comparing your library against minizip with some of my large epub testcases.  If that shows a big enough improvement, I will proceed with the project of converting what you have written to something Qt based.

I will let you know what I see.

Take care.

And Thank You!

**Comment by kevinhendricks** [comment]
BTW, A clone of your repo shows the following:

drwxr-xr-x   4 kbhend  staff   306 15 Jan 14:00 .
drwxr-xr-x  66 kbhend  staff  3740 15 Jan 14:00 ..
drwxr-xr-x   7 kbhend  staff   408 15 Jan 14:00 .git
-rw-r--r--   1 kbhend  staff   355 15 Jan 14:00 .gitignore
-rw-r--r--   1 kbhend  staff   323 15 Jan 14:00 .project.mk
lrwxr-xr-x   1 kbhend  staff    44 15 Jan 14:00 .ycm_extra_conf.py -> /home/dsicilia/dev/nr-make/ycm_extra_conf.py
-rw-r--r--   1 kbhend  staff  1063 15 Jan 14:00 LICENSE.txt
lrwxr-xr-x   1 kbhend  staff    37 15 Jan 14:00 Makefile -> /home/dsicilia/dev/nr-make/nr-make.mk
drwxr-xr-x   2 kbhend  staff   748 15 Jan 14:00 src


Notice the symlinks to places on your local machine.  If you still have those makefile pieces lying around, I would love to see them.

Thanks,

**Comment by no-more-secrets** [comment]
Good luck :-)

Those links are pointing into a bespoke GNU Make-based C++ build system that I wrote a while back and which I used to use for my C++ projects, but which I don't use anymore (nowadays I use CMake).  You can find it here for reference:

https://github.com/dpacbach/nr-make

I'd recommend removing it and just using CMake nowadays, though it looks like you may already be doing that for Sigil.

**Comment by no-more-secrets** [comment]
If you do choose to use the `nr-make` build system during testing, just clone it so that the symlinks point to the right place (the `Makefile` symlink is the only one that matters) and then run:
```
$ make OPT=
```
to build it with optimizations enabled.  It should run properly on the three major platforms (Linux, Mac OS, Windows).

**Comment by no-more-secrets** [comment]
And one more thing regarding `nr-make`: I believe it looks for a user-level config file at `~/.nr-make-rc.mk`.  The one that I use is here:
```
https://github.com/dpacbach/dotfiles/blob/master/dot/nr-make-rc.mk
```
That basically tells it where the compilers are on the system.  Thus as you can see, it may be better to just remove nr-make and write some simple CMake files to build it.

**Comment by kevinhendricks** [comment]
I threw together a quick and dirty CMakeLists.txt and built p-unzip along with libzip.
Ran and timed 10 instances of unpacking the 2500 file test zip via our old internal minizip implementation and and again with all variations of p-unzip using 1, 2, 3, 4, auto, max for threads and even tried a few different distribution policies.

You were absolutely right.  It is IO bound so there was virtually no improvement over the old single thread unzipping code.

So thank you for trying to point me in the right direction.  I appreciate it.

Take care,

Kevin
